package com.yxb.cms.domain.vo;

import com.yxb.cms.domain.dto.PageDto;

import java.io.Serializable;
import java.util.Date;

/**
 * @ Title :
 * @ Description :
 * @ author : yxq(yixin)
 * @ version : 1.0
 * @ DateTime : 2017/11/17 14:44
 */
public class Product extends PageDto implements Serializable {
    private static final long serialVersionUID = 1L;

    public Integer getProductId() {
        return productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public Integer getIsdelete() {
        return isdelete;
    }

    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    public String getCreator() {
        return creator;
    }

    public void setCreator(String creator) {
        this.creator = creator;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getModifier() {
        return modifier;
    }

    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    public Date getModifierTime() {
        return modifierTime;
    }

    public void setModifierTime(Date modifierTime) {
        this.modifierTime = modifierTime;
    }

    private Integer productId;
    private String productName;
    private Integer isdelete;
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_role.create_time
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_role.modifier
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_role.modifier_time
     *
     * @mbggenerated Tue Nov 29 21:23:21 CST 2016
     */
    private Date modifierTime;
}
